import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const dataPath = join(root, 'data', 'roadwatch.json');

const seed = {
  users: [
    { id: 'u_admin', name: 'RoadWatch Super Admin', email: 'admin@roadwatch.in', password: 'admin123', role: 'super_admin', status: 'active', assigned_area: 'Global', assigned_state: 'Maharashtra', assigned_district: 'Pune', assigned_roads: [], created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'u_citizen', name: 'Demo Citizen', email: 'demo@roadwatch.in', password: 'demo1234', role: 'citizen', status: 'active', assigned_area: 'Pune', assigned_state: 'Maharashtra', assigned_district: 'Pune', assigned_roads: [], created_date: '2026-01-05T00:00:00.000Z' },
    { id: 'u_jr1', name: 'Arjun Patil', email: 'junior@roadwatch.in', password: 'junior123', role: 'junior_officer', status: 'active', assigned_area: 'Shivajinagar', assigned_state: 'Maharashtra', assigned_district: 'Pune', assigned_roads: ['pune_road_001', 'pune_road_002'], created_date: '2026-01-10T00:00:00.000Z' },
    { id: 'u_insp1', name: 'Meera Sharma', email: 'inspector@roadwatch.in', password: 'inspect123', role: 'road_inspector', status: 'active', assigned_area: 'Pune Central', assigned_state: 'Maharashtra', assigned_district: 'Pune', assigned_roads: ['pune_road_001', 'pune_road_002', 'pune_road_003'], created_date: '2026-01-12T00:00:00.000Z' },
    { id: 'u_eng1', name: 'Rajesh Kumar', email: 'engineer@roadwatch.in', password: 'engineer123', role: 'executive_engineer', status: 'active', assigned_area: 'Pune Division', assigned_state: 'Maharashtra', assigned_district: 'Pune', assigned_roads: [], created_date: '2026-01-15T00:00:00.000Z' },
    { id: 'u_dist1', name: 'Priya Deshmukh', email: 'district@roadwatch.in', password: 'district123', role: 'district_authority', status: 'active', assigned_area: 'Pune District', assigned_state: 'Maharashtra', assigned_district: 'Pune', assigned_roads: [], created_date: '2026-01-20T00:00:00.000Z' },
    { id: 'u_state1', name: 'Amit Thackeray', email: 'state@roadwatch.in', password: 'state123', role: 'state_authority', status: 'active', assigned_area: 'Maharashtra', assigned_state: 'Maharashtra', assigned_district: '', assigned_roads: [], created_date: '2026-01-22T00:00:00.000Z' },
  ],

  authorities: [
    { id: 'auth_pmc', name: 'Pune Municipal Corporation Road Department', shortName: 'PMC Roads', type: 'Municipal', country: 'India', state: 'Maharashtra', district: 'Pune', wards: ['Shivajinagar-Ghole', 'Aundh-Baner', 'Warje-Karvenagar'], roads: ['pune_road_001', 'pune_road_002', 'pune_road_003', 'pune_road_005', 'pune_road_006'], accountability_score: 84, open_complaints: 17, resolution_rate: 86, response_hours: 9.5, citizen_satisfaction: 82, escalated_complaints: 4, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'auth_nhai', name: 'National Highways Authority of India', shortName: 'NHAI', type: 'National', country: 'India', state: 'Maharashtra', district: 'Pune', wards: ['Hadapsar-Mundhwa'], roads: ['pune_road_007'], accountability_score: 90, open_complaints: 8, resolution_rate: 91, response_hours: 7.8, citizen_satisfaction: 88, escalated_complaints: 2, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'auth_pmrda', name: 'Pune Metropolitan Region Development Authority', shortName: 'PMRDA', type: 'Metropolitan', country: 'India', state: 'Maharashtra', district: 'Pune', wards: ['Kothrud-Bawdhan'], roads: ['pune_road_004'], accountability_score: 62, open_complaints: 24, resolution_rate: 63, response_hours: 18.2, citizen_satisfaction: 61, escalated_complaints: 9, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'auth_ladot', name: 'Los Angeles Department of Transportation', shortName: 'LADOT', type: 'Municipal', country: 'USA', state: 'California', district: 'Los Angeles', wards: ['Downtown', 'Hollywood'], roads: ['us_road_001'], accountability_score: 78, open_complaints: 12, resolution_rate: 80, response_hours: 14.0, citizen_satisfaction: 74, escalated_complaints: 3, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'auth_tfl', name: 'Transport for London - Highways', shortName: 'TfL Roads', type: 'National', country: 'UK', state: 'England', district: 'London', wards: ['City of London'], roads: ['uk_road_001'], accountability_score: 88, open_complaints: 6, resolution_rate: 93, response_hours: 6.2, citizen_satisfaction: 89, escalated_complaints: 1, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'auth_rta', name: 'Roads and Transport Authority Dubai', shortName: 'RTA Dubai', type: 'Government', country: 'UAE', state: 'Dubai', district: 'Dubai Central', wards: ['Downtown Dubai'], roads: ['me_road_001'], accountability_score: 95, open_complaints: 3, resolution_rate: 97, response_hours: 4.5, citizen_satisfaction: 94, escalated_complaints: 0, created_date: '2026-01-01T00:00:00.000Z' },
  ],

  contractors: [
    { id: 'con_001', name: 'PMC Infrastructure Ltd.', company_type: 'Private Limited', country: 'India', state: 'Maharashtra', contact_details: 'contact@pmcinfra.in | +91-20-1234-5678', projects_completed: 42, projects_active: 3, complaint_count: 5, avg_health_score: 83, resolution_rate: 94, citizen_rating: 4.7, reliability_score: 92, repair_completion_rate: 96, allocated_budget: 62000000, spent_budget: 47000000, assigned_roads: ['pune_road_001', 'pune_road_005'], authority: 'Pune Municipal Corporation Road Department', accountability_score: 91, project_status: 'Active', start_date: '2025-01-01', completion_date: '2026-12-31', created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'con_002', name: 'Maharashtra Road Builders (MRB)', company_type: 'Govt Contractor Class A', country: 'India', state: 'Maharashtra', contact_details: 'mrb@gov.in | +91-20-2345-6789', projects_completed: 31, projects_active: 5, complaint_count: 14, avg_health_score: 46, resolution_rate: 61, citizen_rating: 3.1, reliability_score: 55, repair_completion_rate: 68, allocated_budget: 18000000, spent_budget: 14500000, assigned_roads: ['pune_road_002'], authority: 'Pune Municipal Corporation Road Department', accountability_score: 57, project_status: 'Active', start_date: '2025-03-01', completion_date: '2026-06-30', created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'con_003', name: 'Pune Smartways & Co.', company_type: 'Private Limited', country: 'India', state: 'Maharashtra', contact_details: 'info@smartways.co.in | +91-20-3456-7890', projects_completed: 28, projects_active: 2, complaint_count: 6, avg_health_score: 83, resolution_rate: 89, citizen_rating: 4.4, reliability_score: 89, repair_completion_rate: 91, allocated_budget: 116000000, spent_budget: 108000000, assigned_roads: ['pune_road_003', 'pune_road_007'], authority: 'NHAI Pune Regional Office', accountability_score: 88, project_status: 'Active', start_date: '2025-06-01', completion_date: '2027-03-31', created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'con_004', name: 'Western India Highways Ltd.', company_type: 'Public Limited', country: 'India', state: 'Gujarat/Maharashtra', contact_details: 'wih@highways.in | +91-79-4567-8901', projects_completed: 55, projects_active: 7, complaint_count: 29, avg_health_score: 28, resolution_rate: 38, citizen_rating: 2.2, reliability_score: 35, repair_completion_rate: 47, allocated_budget: 45000000, spent_budget: 41000000, assigned_roads: ['pune_road_004'], authority: 'Pune Metropolitan Region Development Authority', accountability_score: 37, project_status: 'Delayed', start_date: '2024-10-01', completion_date: '2025-12-31', created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'con_005', name: 'BuildRight Contractors', company_type: 'Partnership Firm', country: 'India', state: 'Maharashtra', contact_details: 'buildright@construction.in | +91-20-5678-9012', projects_completed: 18, projects_active: 4, complaint_count: 19, avg_health_score: 61, resolution_rate: 72, citizen_rating: 3.6, reliability_score: 68, repair_completion_rate: 76, allocated_budget: 27000000, spent_budget: 23200000, assigned_roads: ['pune_road_006'], authority: 'Pune Municipal Corporation Road Department', accountability_score: 70, project_status: 'Active', start_date: '2025-04-01', completion_date: '2026-09-30', created_date: '2026-01-01T00:00:00.000Z' },
  ],

  roads: [
    { id: 'pune_road_001', country: 'India', state: 'Maharashtra', district: 'Pune', ward: 'Shivajinagar-Ghole Road Ward Office', name: 'Jangali Maharaj (JM) Road', road_code: 'PMC-URB-01', road_type: 'Urban Street', length_km: 1.8, health_score: 89, status: 'Excellent', contractor_id: 'con_001', contractor_name: 'PMC Infrastructure Ltd.', authority_id: 'auth_pmc', authority_name: 'Pune Municipal Corporation Road Department', allocated_budget: 24000000, spent_budget: 18000000, budget_remaining: 6000000, funding_source: 'PMC Capital Works Fund', coordinates: [[18.5185, 73.8543], [18.5202, 73.8517], [18.5218, 73.8495], [18.5235, 73.8468]], last_repair_date: '2026-02-15', construction_date: '2022-04-10', traffic_density: 'High', total_complaints: 2, active_complaints: 0, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'pune_road_002', country: 'India', state: 'Maharashtra', district: 'Pune', ward: 'Shivajinagar-Ghole Road Ward Office', name: 'Fergusson College (FC) Road', road_code: 'PMC-URB-02', road_type: 'Urban Street', length_km: 2.1, health_score: 46, status: 'Poor', contractor_id: 'con_002', contractor_name: 'Maharashtra Road Builders (MRB)', authority_id: 'auth_pmc', authority_name: 'Pune Municipal Corporation Road Department', allocated_budget: 18000000, spent_budget: 14500000, budget_remaining: 3500000, funding_source: 'Pune Smart City Grant', coordinates: [[18.5205, 73.8452], [18.5235, 73.8445], [18.5255, 73.8436], [18.5285, 73.8415]], last_repair_date: '2025-11-20', construction_date: '2021-08-15', traffic_density: 'Very High', total_complaints: 14, active_complaints: 8, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'pune_road_003', country: 'India', state: 'Maharashtra', district: 'Pune', ward: 'Shivajinagar-Ghole Road Ward Office', name: 'Senapati Bapat (SB) Road', road_code: 'PMC-URB-03', road_type: 'Urban Arterial', length_km: 2.5, health_score: 72, status: 'Good', contractor_id: 'con_003', contractor_name: 'Pune Smartways & Co.', authority_id: 'auth_pmc', authority_name: 'Pune Municipal Corporation Road Department', allocated_budget: 31000000, spent_budget: 27000000, budget_remaining: 4000000, funding_source: 'State Infrastructure Fund', coordinates: [[18.5265, 73.8375], [18.5305, 73.8325], [18.5345, 73.8285]], last_repair_date: '2026-03-05', construction_date: '2023-01-20', traffic_density: 'High', total_complaints: 5, active_complaints: 2, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'pune_road_004', country: 'India', state: 'Maharashtra', district: 'Pune', ward: 'Kothrud-Bawdhan Ward Office', name: 'Karve Road (Nal Stop Segment)', road_code: 'PMC-MDR-01', road_type: 'Major District Road', length_km: 3.4, health_score: 28, status: 'Closed', contractor_id: 'con_004', contractor_name: 'Western India Highways Ltd.', authority_id: 'auth_pmrda', authority_name: 'Pune Metropolitan Region Development Authority', allocated_budget: 45000000, spent_budget: 41000000, budget_remaining: 4000000, funding_source: 'National Highway Authority Aid', coordinates: [[18.5135, 73.8425], [18.5095, 73.8325], [18.5055, 73.8215]], last_repair_date: '2025-05-12', construction_date: '2019-11-10', traffic_density: 'Extreme', total_complaints: 29, active_complaints: 17, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'pune_road_005', country: 'India', state: 'Maharashtra', district: 'Pune', ward: 'Aundh-Baner Ward Office', name: 'Baner Road (Aundh-Baner link)', road_code: 'PMC-URB-04', road_type: 'Urban Street', length_km: 4.2, health_score: 78, status: 'Good', contractor_id: 'con_001', contractor_name: 'PMC Infrastructure Ltd.', authority_id: 'auth_pmc', authority_name: 'Pune Municipal Corporation Road Department', allocated_budget: 38000000, spent_budget: 29000000, budget_remaining: 9000000, funding_source: 'PMC Capital Works Fund', coordinates: [[18.5395, 73.8205], [18.5495, 73.7995], [18.5595, 73.7805]], last_repair_date: '2026-01-10', construction_date: '2023-09-05', traffic_density: 'Medium', total_complaints: 6, active_complaints: 1, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'pune_road_006', country: 'India', state: 'Maharashtra', district: 'Pune', ward: 'Warje-Karvenagar Ward Office', name: 'Sinhagad Road (Dandekar Bridge)', road_code: 'PMC-MDR-02', road_type: 'Major District Road', length_km: 3.8, health_score: 61, status: 'Moderate', contractor_id: 'con_005', contractor_name: 'BuildRight Contractors', authority_id: 'auth_pmc', authority_name: 'Pune Municipal Corporation Road Department', allocated_budget: 27000000, spent_budget: 23200000, budget_remaining: 3800000, funding_source: 'PMC Capital Works Fund', coordinates: [[18.5035, 73.8385], [18.4905, 73.8215], [18.4755, 73.8055]], last_repair_date: '2025-08-30', construction_date: '2020-07-22', traffic_density: 'Very High', total_complaints: 19, active_complaints: 6, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'pune_road_007', country: 'India', state: 'Maharashtra', district: 'Pune', ward: 'Hadapsar-Mundhwa Ward Office', name: 'Pune-Solapur Road (Hadapsar)', road_code: 'PMC-NH-01', road_type: 'National Highway Segment', length_km: 5.6, health_score: 94, status: 'Excellent', contractor_id: 'con_003', contractor_name: 'Pune Smartways & Co.', authority_id: 'auth_nhai', authority_name: 'National Highways Authority of India', allocated_budget: 85000000, spent_budget: 81000000, budget_remaining: 4000000, funding_source: 'National Highway Authority Aid', coordinates: [[18.5065, 73.8755], [18.5042, 73.9056], [18.5015, 73.9355]], last_repair_date: '2026-04-18', construction_date: '2024-05-10', traffic_density: 'Extreme', total_complaints: 1, active_complaints: 0, created_date: '2026-01-01T00:00:00.000Z' },
    // Global roads
    { id: 'us_road_001', country: 'USA', state: 'California', district: 'Los Angeles', ward: 'Downtown', name: 'Figueroa Street (Downtown LA)', road_code: 'LA-URB-01', road_type: 'Urban Arterial', length_km: 3.2, health_score: 67, status: 'Moderate', contractor_id: null, contractor_name: 'SoCal Paving Group', authority_id: 'auth_ladot', authority_name: 'Los Angeles Department of Transportation', allocated_budget: 1200000, spent_budget: 980000, budget_remaining: 220000, funding_source: 'LA City Infrastructure Bond', coordinates: [[34.0522, -118.2487], [34.0555, -118.2490], [34.0590, -118.2494]], last_repair_date: '2025-09-15', construction_date: '2018-03-10', traffic_density: 'Very High', total_complaints: 12, active_complaints: 5, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'uk_road_001', country: 'UK', state: 'England', district: 'London', ward: 'City of London', name: 'London Wall (City)', road_code: 'TFL-CITY-01', road_type: 'Urban Arterial', length_km: 1.4, health_score: 88, status: 'Excellent', contractor_id: null, contractor_name: 'Balfour Beatty Highways', authority_id: 'auth_tfl', authority_name: 'Transport for London - Highways', allocated_budget: 850000, spent_budget: 720000, budget_remaining: 130000, funding_source: 'TfL Capital Investment Programme', coordinates: [[51.5156, -0.0922], [51.5162, -0.0898], [51.5168, -0.0874]], last_repair_date: '2026-01-20', construction_date: '2015-06-01', traffic_density: 'High', total_complaints: 3, active_complaints: 0, created_date: '2026-01-01T00:00:00.000Z' },
    { id: 'me_road_001', country: 'UAE', state: 'Dubai', district: 'Dubai Central', ward: 'Downtown Dubai', name: 'Sheikh Zayed Road (D89)', road_code: 'RTA-E11-01', road_type: 'Expressway', length_km: 12.8, health_score: 97, status: 'Excellent', contractor_id: null, contractor_name: 'ALEC Engineering', authority_id: 'auth_rta', authority_name: 'Roads and Transport Authority Dubai', allocated_budget: 15000000, spent_budget: 12500000, budget_remaining: 2500000, funding_source: 'Dubai Government Infrastructure Fund', coordinates: [[25.1972, 55.2744], [25.2048, 55.2712], [25.2124, 55.2680]], last_repair_date: '2026-03-01', construction_date: '2010-01-01', traffic_density: 'Extreme', total_complaints: 2, active_complaints: 0, created_date: '2026-01-01T00:00:00.000Z' },
  ],

  repairs: [
    { id: 'rep_001', road_id: 'pune_road_001', road_name: 'Jangali Maharaj (JM) Road', event_type: 'Repair Completed', repair_type: 'Pothole milling and asphalt overlay', description: 'Multiple edge cracks near Deccan Gymkhana crossing repaired. Surface restored, lane markings repainted.', repair_cost: 1800000, contractor: 'PMC Infrastructure Ltd.', authority: 'Pune Municipal Corporation Road Department', event_date: '2026-02-15T00:00:00.000Z', before_repair: 'Multiple edge cracks near Deccan Gymkhana crossing', after_repair: 'Surface restored, lane markings repainted, no active complaints', created_date: '2026-02-15T00:00:00.000Z' },
    { id: 'rep_002', road_id: 'pune_road_002', road_name: 'Fergusson College (FC) Road', event_type: 'Repair Completed', repair_type: 'Storm-drain clearing with asphalt patching', description: 'Drain partially cleared; repeat complaints remain under review.', repair_cost: 3200000, contractor: 'Maharashtra Road Builders (MRB)', authority: 'Pune Municipal Corporation Road Department', event_date: '2025-11-20T00:00:00.000Z', before_repair: 'Waterlogging and exposed aggregate near FC gate', after_repair: 'Drain partially cleared; repeat complaints remain under review', created_date: '2025-11-20T00:00:00.000Z' },
    { id: 'rep_003', road_id: 'pune_road_003', road_name: 'Senapati Bapat (SB) Road', event_type: 'Repair Completed', repair_type: 'Sub-base stabilization and resurfacing', description: 'Sub-base compacted, surface evenness improved by 31%.', repair_cost: 4200000, contractor: 'Pune Smartways & Co.', authority: 'Pune Municipal Corporation Road Department', event_date: '2026-03-05T00:00:00.000Z', before_repair: 'Fatigue cracking and slow road subsidence', after_repair: 'Sub-base compacted, surface evenness improved by 31%', created_date: '2026-03-05T00:00:00.000Z' },
    { id: 'rep_004', road_id: 'pune_road_004', road_name: 'Karve Road (Nal Stop Segment)', event_type: 'Repair Completed', repair_type: 'Speed-breaker correction and safety repaint', description: 'Reflective paint added; surface deterioration still high risk.', repair_cost: 7600000, contractor: 'Western India Highways Ltd.', authority: 'Pune Metropolitan Region Development Authority', event_date: '2025-05-12T00:00:00.000Z', before_repair: 'Unpainted speed breaker and unsafe jolts', after_repair: 'Reflective paint added; surface deterioration still high risk', created_date: '2025-05-12T00:00:00.000Z' },
    { id: 'rep_005', road_id: 'pune_road_005', road_name: 'Baner Road (Aundh-Baner link)', event_type: 'Repair Completed', repair_type: 'Hotmix pothole repair', description: 'Main lane repaired, shoulder patch pending.', repair_cost: 2600000, contractor: 'PMC Infrastructure Ltd.', authority: 'Pune Municipal Corporation Road Department', event_date: '2026-01-10T00:00:00.000Z', before_repair: 'Pothole outbreak near Westend Mall', after_repair: 'Main lane repaired, shoulder patch pending', created_date: '2026-01-10T00:00:00.000Z' },
    { id: 'rep_006', road_id: 'pune_road_002', road_name: 'Fergusson College (FC) Road', event_type: 'Inspection', repair_type: 'Site Inspection', description: 'Inspection revealed 14 active potholes, waterlogging persists. Escalated to Executive Engineer.', repair_cost: 0, contractor: 'Maharashtra Road Builders (MRB)', authority: 'Pune Municipal Corporation Road Department', event_date: '2026-01-15T00:00:00.000Z', before_repair: 'Ongoing deterioration', after_repair: 'Inspection report submitted, work order pending', created_date: '2026-01-15T00:00:00.000Z' },
  ],

  budgets: [
    { id: 'bud_001', road_id: 'pune_road_001', road_name: 'JM Road', authority_id: 'auth_pmc', contractor_id: 'con_001', allocated: 24000000, spent: 18000000, remaining: 6000000, funding_source: 'PMC Capital Works Fund', financial_year: '2025-26', status: 'Active', last_updated: '2026-02-15T00:00:00.000Z', created_date: '2025-04-01T00:00:00.000Z' },
    { id: 'bud_002', road_id: 'pune_road_002', road_name: 'FC Road', authority_id: 'auth_pmc', contractor_id: 'con_002', allocated: 18000000, spent: 14500000, remaining: 3500000, funding_source: 'Pune Smart City Grant', financial_year: '2025-26', status: 'Active', last_updated: '2025-11-20T00:00:00.000Z', created_date: '2025-04-01T00:00:00.000Z' },
    { id: 'bud_003', road_id: 'pune_road_003', road_name: 'SB Road', authority_id: 'auth_pmc', contractor_id: 'con_003', allocated: 31000000, spent: 27000000, remaining: 4000000, funding_source: 'State Infrastructure Fund', financial_year: '2025-26', status: 'Active', last_updated: '2026-03-05T00:00:00.000Z', created_date: '2025-04-01T00:00:00.000Z' },
    { id: 'bud_004', road_id: 'pune_road_004', road_name: 'Karve Road', authority_id: 'auth_pmrda', contractor_id: 'con_004', allocated: 45000000, spent: 41000000, remaining: 4000000, funding_source: 'National Highway Authority Aid', financial_year: '2025-26', status: 'Overspent Risk', last_updated: '2025-05-12T00:00:00.000Z', created_date: '2025-04-01T00:00:00.000Z' },
    { id: 'bud_005', road_id: 'pune_road_005', road_name: 'Baner Road', authority_id: 'auth_pmc', contractor_id: 'con_001', allocated: 38000000, spent: 29000000, remaining: 9000000, funding_source: 'PMC Capital Works Fund', financial_year: '2025-26', status: 'On Track', last_updated: '2026-01-10T00:00:00.000Z', created_date: '2025-04-01T00:00:00.000Z' },
    { id: 'bud_006', road_id: 'pune_road_006', road_name: 'Sinhagad Road', authority_id: 'auth_pmc', contractor_id: 'con_005', allocated: 27000000, spent: 23200000, remaining: 3800000, funding_source: 'PMC Capital Works Fund', financial_year: '2025-26', status: 'Active', last_updated: '2025-08-30T00:00:00.000Z', created_date: '2025-04-01T00:00:00.000Z' },
    { id: 'bud_007', road_id: 'pune_road_007', road_name: 'Pune-Solapur Road', authority_id: 'auth_nhai', contractor_id: 'con_003', allocated: 85000000, spent: 81000000, remaining: 4000000, funding_source: 'National Highway Authority Aid', financial_year: '2025-26', status: 'Active', last_updated: '2026-04-18T00:00:00.000Z', created_date: '2025-04-01T00:00:00.000Z' },
  ],

  complaints: [
    { id: 'pune_cmp_1', title: 'Deep pothole cluster near Deccan Gymkhana crossing', description: 'A series of 4 deep potholes have opened up right on the pedestrian crossing near Deccan Gymkhana. Extremely dangerous for two-wheelers, especially during night-time.', severity: 'Critical', status: 'Submitted', category: 'Road Damage', location_text: 'Jangali Maharaj (JM) Road, near Deccan Gymkhana, Pune', district: 'Pune', state: 'Maharashtra', country: 'India', latitude: 18.5202, longitude: 73.8495, road_id: 'pune_road_001', road_name: 'Jangali Maharaj (JM) Road', ward: 'Shivajinagar-Ghole Road Ward Office', authority: 'Pune Municipal Corporation Road Department', contractor_id: 'con_001', contractor_name: 'PMC Infrastructure Ltd.', upvote_count: 42, ai_confidence: 0.89, ai_verification_status: 'AI Verified', detected_issue_type: 'Pothole', severity_prediction: 'Critical', verification_count: 31, duplicate_count: 2, confirm_count: 24, incorrect_count: 1, community_confidence_score: 92, verification_status: 'Verified by Community', created_date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), updated_date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
    { id: 'pune_cmp_2', title: 'Waterlogging and asphalt washing away near FC gate', description: 'Major waterlogging occurring near the Fergusson College gate due to a blocked storm-drain.', severity: 'High', status: 'In Progress', category: 'Flooding', location_text: 'Fergusson College (FC) Road, opposite main gate, Pune', district: 'Pune', state: 'Maharashtra', country: 'India', latitude: 18.5235, longitude: 73.8445, road_id: 'pune_road_002', road_name: 'Fergusson College (FC) Road', ward: 'Shivajinagar-Ghole Road Ward Office', authority: 'Pune Municipal Corporation Road Department', contractor_id: 'con_002', contractor_name: 'Maharashtra Road Builders (MRB)', upvote_count: 28, ai_confidence: 0.74, ai_verification_status: 'Under Review', detected_issue_type: 'Waterlogging', severity_prediction: 'High', verification_count: 18, duplicate_count: 4, confirm_count: 16, incorrect_count: 2, community_confidence_score: 76, verification_status: 'Under Review', created_date: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(), updated_date: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString() },
    { id: 'pune_cmp_3', title: 'Asphalt cracking and road subsidence near Symbiosis', description: 'A large section of SB road near Symbiosis is sinking slowly. Extensive fatigue cracks have formed over a 20-meter stretch.', severity: 'Medium', status: 'Resolved', category: 'Road Damage', location_text: 'Senapati Bapat (SB) Road, near Symbiosis Institute, Pune', district: 'Pune', state: 'Maharashtra', country: 'India', latitude: 18.5305, longitude: 73.8325, road_id: 'pune_road_003', road_name: 'Senapati Bapat (SB) Road', ward: 'Shivajinagar-Ghole Road Ward Office', authority: 'Pune Municipal Corporation Road Department', contractor_id: 'con_003', contractor_name: 'Pune Smartways & Co.', upvote_count: 15, ai_confidence: 0.91, ai_verification_status: 'AI Verified', detected_issue_type: 'Road Crack', severity_prediction: 'Medium', verification_count: 12, duplicate_count: 0, confirm_count: 11, incorrect_count: 0, community_confidence_score: 88, verification_status: 'Verified by Community', created_date: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(), updated_date: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString() },
    { id: 'pune_cmp_4', title: 'Severe road surface deterioration near Westend Mall', description: 'Heavy commuter traffic has caused pothole outbreaks on the main lane of Baner Road right in front of Westend Mall.', severity: 'High', status: 'Submitted', category: 'Road Damage', location_text: 'Baner Road, opposite Westend Mall, Pune', district: 'Pune', state: 'Maharashtra', country: 'India', latitude: 18.5495, longitude: 73.7995, road_id: 'pune_road_005', road_name: 'Baner Road (Aundh-Baner link)', ward: 'Aundh-Baner Ward Office', authority: 'Pune Municipal Corporation Road Department', contractor_id: 'con_001', contractor_name: 'PMC Infrastructure Ltd.', upvote_count: 34, ai_confidence: 0.85, ai_verification_status: 'AI Verified', detected_issue_type: 'Unsafe Surface', severity_prediction: 'High', verification_count: 21, duplicate_count: 1, confirm_count: 19, incorrect_count: 1, community_confidence_score: 84, verification_status: 'AI Verified', created_date: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(), updated_date: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString() },
    { id: 'pune_cmp_5', title: 'Damaged and unpainted speed breaker causing severe jolts', description: 'The newly constructed speed breaker near Nal Stop is unpainted and does not have reflective markers.', severity: 'Critical', status: 'In Progress', category: 'Safety', location_text: 'Karve Road, Nal Stop Flyover underpass, Pune', district: 'Pune', state: 'Maharashtra', country: 'India', latitude: 18.5095, longitude: 73.8325, road_id: 'pune_road_004', road_name: 'Karve Road (Nal Stop Segment)', ward: 'Kothrud-Bawdhan Ward Office', authority: 'Pune Metropolitan Region Development Authority', contractor_id: 'con_004', contractor_name: 'Western India Highways Ltd.', upvote_count: 57, ai_confidence: 0.95, ai_verification_status: 'AI Verified', detected_issue_type: 'Broken Divider', severity_prediction: 'Critical', verification_count: 44, duplicate_count: 6, confirm_count: 39, incorrect_count: 1, community_confidence_score: 94, verification_status: 'Duplicate Report', created_date: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), updated_date: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString() },
    { id: 'pune_cmp_6', title: 'Large sinkhole forming on Sinhagad Road near bridge', description: 'A sinkhole approximately 1.5m wide is forming on the side of Sinhagad Road near Dandekar Bridge. Vehicles driving close to the edge are at risk.', severity: 'Critical', status: 'Escalated', category: 'Road Damage', location_text: 'Sinhagad Road, near Dandekar Bridge, Pune', district: 'Pune', state: 'Maharashtra', country: 'India', latitude: 18.4905, longitude: 73.8215, road_id: 'pune_road_006', road_name: 'Sinhagad Road (Dandekar Bridge)', ward: 'Warje-Karvenagar Ward Office', authority: 'Pune Municipal Corporation Road Department', contractor_id: 'con_005', contractor_name: 'BuildRight Contractors', upvote_count: 63, ai_confidence: 0.93, ai_verification_status: 'AI Verified', detected_issue_type: 'Sinkhole', severity_prediction: 'Critical', verification_count: 28, duplicate_count: 0, confirm_count: 27, incorrect_count: 1, community_confidence_score: 96, verification_status: 'Verified by Community', created_date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), updated_date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
    { id: 'us_cmp_1', title: 'Severe pothole damage on Figueroa Street near Convention Center', description: 'Multiple deep potholes have formed on the northbound lane of Figueroa Street, causing tire damage to vehicles.', severity: 'High', status: 'Submitted', category: 'Road Damage', location_text: 'Figueroa Street, near Convention Center, Los Angeles, CA', district: 'Los Angeles', state: 'California', country: 'USA', latitude: 34.0555, longitude: -118.2490, road_id: 'us_road_001', road_name: 'Figueroa Street (Downtown LA)', ward: 'Downtown', authority: 'Los Angeles Department of Transportation', contractor_id: null, contractor_name: 'SoCal Paving Group', upvote_count: 18, ai_confidence: 0.82, ai_verification_status: 'AI Verified', detected_issue_type: 'Pothole', severity_prediction: 'High', verification_count: 9, duplicate_count: 1, confirm_count: 8, incorrect_count: 0, community_confidence_score: 78, verification_status: 'Verified by Community', created_date: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(), updated_date: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString() },
  ],

  forums: [
    { id: 'forum_001', road_id: 'pune_road_001', road_name: 'Jangali Maharaj (JM) Road', road_code: 'PMC-URB-01', road_district: 'Pune', road_state: 'Maharashtra', road_health: 89, author_id: 'u_citizen', author_name: 'Demo Citizen', author_level: 'road_reporter', author_points: 140, title: 'Pothole near Deccan Gymkhana still unrepaired — danger to two-wheelers', subject_category: 'ROAD_DAMAGE', content: 'Despite my complaint filed 3 days ago, the pothole cluster near Deccan Gymkhana has not been attended to. Two-wheeler riders have narrowly escaped accidents. The PMC needs to prioritize this urgent fix.', upvote_count: 42, downvote_count: 3, comment_count: 8, view_count: 412, score: 98.2, is_pinned: false, is_supervoted: false, is_trending: true, is_locked: false, is_hidden: false, media: [], created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), updated_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(), created_date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString() },
    { id: 'forum_002', road_id: 'pune_road_004', road_name: 'Karve Road (Nal Stop Segment)', road_code: 'PMC-MDR-01', road_district: 'Pune', road_state: 'Maharashtra', road_health: 28, author_id: 'u_jr1', author_name: 'Arjun Patil', author_level: 'road_guardian', author_points: 310, title: 'URGENT: Karve Road completely closed — no alternative route signage', subject_category: 'REPAIR_DELAY', content: 'Karve Road has been closed for emergency repair for 6 days now. There is zero signage for alternate routes and traffic police are nowhere to be seen. This is causing 45-minute delays during peak hours. PMRDA must act immediately.', upvote_count: 127, downvote_count: 4, comment_count: 34, view_count: 1240, score: 287.1, is_pinned: true, is_supervoted: true, is_trending: true, is_locked: false, is_hidden: false, supervoted_by: 'u_dist1', supervoted_by_name: 'District Authority, Pune', supervoted_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), pinned_by: 'u_admin', pinned_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), media: [], created_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(), updated_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(), created_date: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString() },
    { id: 'forum_003', road_id: 'pune_road_002', road_name: 'Fergusson College (FC) Road', road_code: 'PMC-URB-02', road_district: 'Pune', road_state: 'Maharashtra', road_health: 46, author_id: 'u_citizen', author_name: 'Demo Citizen', author_level: 'road_scout', author_points: 85, title: 'FC Road flooding every monsoon — drainage never fixed', subject_category: 'FLOODING', content: 'Every monsoon without fail, FC Road becomes a lake near the main gate. The PWD has allocated budget for drainage repair three years running, but no work ever happens. I have RTI proof of ₹1.2 Crore allocated but unspent.', upvote_count: 64, downvote_count: 2, comment_count: 18, view_count: 521, score: 143.1, is_pinned: false, is_supervoted: false, is_trending: false, is_locked: false, is_hidden: false, media: [], created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(), updated_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(), created_date: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString() },
  ],

  notifications: [
    { id: 'notif_001', user_id: 'u_citizen', title: '🔍 AI Analysis Complete', body: 'Your complaint "Deep pothole cluster near Deccan Gymkhana" has been verified by AI with 89% confidence.', priority: 'high', type: 'ai_analysis', is_read: false, created_date: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
    { id: 'notif_002', user_id: 'u_citizen', title: '✅ Complaint Verified', body: 'Community has verified your complaint on JM Road. Status updated to "AI Verified".', priority: 'medium', type: 'complaint_update', is_read: false, created_date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
    { id: 'notif_003', user_id: 'u_jr1', title: '🆕 New Complaint Assigned', body: '3 new complaints require verification in Shivajinagar-Ghole ward.', priority: 'high', type: 'assignment', is_read: false, created_date: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString() },
    { id: 'notif_004', user_id: 'u_eng1', title: '⚠️ Budget Alert', body: 'FC Road (PMC-URB-02) budget utilization has reached 80%. Review spending status.', priority: 'medium', type: 'budget_alert', is_read: true, created_date: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
  ],

  aiAnalyses: [
    { id: 'ai_001', complaint_id: 'pune_cmp_1', road_id: 'pune_road_001', issue_type: 'Pothole', confidence: 0.89, severity_score: 8.4, duplicate_detection: false, bounding_boxes: [{ x: 120, y: 80, w: 200, h: 150, label: 'Pothole Cluster', confidence: 0.89 }], detected_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), created_date: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
    { id: 'ai_002', complaint_id: 'pune_cmp_2', road_id: 'pune_road_002', issue_type: 'Waterlogging', confidence: 0.74, severity_score: 7.1, duplicate_detection: false, bounding_boxes: [{ x: 50, y: 120, w: 300, h: 200, label: 'Waterlogged Section', confidence: 0.74 }], detected_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(), created_date: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString() },
    { id: 'ai_003', complaint_id: 'pune_cmp_3', road_id: 'pune_road_003', issue_type: 'Road Crack', confidence: 0.91, severity_score: 5.8, duplicate_detection: false, bounding_boxes: [{ x: 80, y: 100, w: 250, h: 80, label: 'Alligator Cracking', confidence: 0.91 }], detected_at: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(), created_date: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString() },
    { id: 'ai_004', complaint_id: 'pune_cmp_5', road_id: 'pune_road_004', issue_type: 'Broken Divider', confidence: 0.95, severity_score: 9.1, duplicate_detection: true, bounding_boxes: [{ x: 60, y: 90, w: 180, h: 120, label: 'Unpainted Speed Breaker', confidence: 0.95 }], detected_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(), created_date: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString() },
    { id: 'ai_005', complaint_id: 'pune_cmp_6', road_id: 'pune_road_006', issue_type: 'Sinkhole', confidence: 0.93, severity_score: 9.8, duplicate_detection: false, bounding_boxes: [{ x: 140, y: 60, w: 160, h: 160, label: 'Sinkhole Formation', confidence: 0.93 }], detected_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(), created_date: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString() },
  ],

  dataSources: [
    { id: 'osm', name: 'OpenStreetMap', type: 'Base Map', trust: 'High', description: 'Global open map data' },
    { id: 'municipal', name: 'Municipal Data', type: 'Authority Records', trust: 'Official', description: 'Direct from municipal corporations' },
    { id: 'pwd', name: 'PWD Records', type: 'Road Records', trust: 'Official', description: 'Public Works Department road data' },
    { id: 'citizen', name: 'Citizen Reports', type: 'Crowdsourced', trust: 'Community Validated', description: 'Verified community reports' },
    { id: 'ai', name: 'AI Detection', type: 'Computer Vision', trust: 'Model Scored', description: 'Computer vision road analysis' },
    { id: 'repair', name: 'Repair Records', type: 'Works Ledger', trust: 'Audited', description: 'Contractor work completion records' },
    { id: 'budget', name: 'Budget Records', type: 'Finance Ledger', trust: 'Audited', description: 'Government financial allocations' },
    { id: 'tender', name: 'Tender Records', type: 'Contract Ledger', trust: 'Official', description: 'Public contract award records' },
  ],
  datasets: [],
  cities: [],
  wards: [],
};

export async function readStore() {
  try {
    return normalizeStore(JSON.parse(await readFile(dataPath, 'utf8')));
  } catch {
    await mkdir(dirname(dataPath), { recursive: true });
    // Resolve the dynamic Date.now() calls in seed
    const resolved = JSON.parse(JSON.stringify(seed));
    await writeStore(resolved);
    return structuredClone(resolved);
  }
}

export async function writeStore(data) {
  await mkdir(dirname(dataPath), { recursive: true });
  await writeFile(dataPath, JSON.stringify(data, null, 2));
}

export async function mutateStore(mutator) {
  const data = await readStore();
  const result = await mutator(data);
  await writeStore(data);
  return result;
}

export function id(prefix) {
  return `${prefix}_${Math.random().toString(36).slice(2, 10)}`;
}

function normalizeStore(data) {
  return {
    ...data,
    users: data.users || [],
    complaints: data.complaints || [],
    roads: data.roads || [],
    contractors: data.contractors || [],
    authorities: data.authorities || [],
    budgets: data.budgets || [],
    repairs: data.repairs || [],
    forums: data.forums || [],
    notifications: data.notifications || [],
    aiAnalyses: data.aiAnalyses || [],
    dataSources: data.dataSources || [],
    datasets: data.datasets || [],
    cities: data.cities || [],
    wards: data.wards || [],
  };
}
